### ISSUE TITLE
Check if the location of tmp flask files could be specified somewhere

### ISSUE THREAD

**Issue by kbalog** [iai-group/arXivDigest#33] opened 2020-02-14 11:04 UTC
```
[Fri Feb 14 12:01:23.407380 2020] [wsgi:error] [pid 5119] [remote 152.94.11.12:64192] PermissionError: [Errno 13] Permission denied: '/opt/anaconda3/lib/python3.6/site-packages/frontend/static/.webassets-cache'
```

**Comment by oyvi96** [comment] 2020-02-17 00:50
@kbalog 
The first error here is caused by the caching mechanism in flask assets. Im both able to move the cache or stop caching completely. 

Next a bundled javascript file will be created, I'm able to set this location to an absolute path or a path relative to the package install. 

If we move this bundle location to a static folder managed by apache we should probably also move the other static files (css and icons). These would have to be updated manually when updating the application or moved by the flask app on startup.  

1. Would you want a a variabel in the config to set the path for the static folder used by apache such that the file is generated in the correct location? 

2. And should we disable caching or have a configurable path for this?

3. Lastly should the other static files be moved automatically, updated manually or stay as is but then having to have a more advanced configuration of static file serving in apache?

**Comment by oyvi96** [comment] 2020-02-28 15:24
@kbalog Just a reminder that the system probably won't be able to run before this is fixed. So I need to know the answers to the above questions in regards to what locations and settings to use that will interfere the least with deployment to gustav, thinking about the active security policies.

**Comment by kbalog** [comment] 2020-02-28 21:45
My preferred solution would be to have a separate folder for the cache files which is defined in a config variable. The remaining files could stay as is (i.e., part of the package).

Alternatively, it's also OK is static files are updated manually in a given location (specified in a config variable) and have the cache folder automatically set within that location. But, then, they should probably be moved outside the package to avoid duplication. Also, it should also mean not only the static files but templates too (so that the entire html-css-js part of the frontend becomes independent of the package).

**Comment by oyvi96** [comment] 2020-02-29 16:29
@kbalog 
A config for cache path is good. 

The problem with leaving the other files as is, is that the javascript files will be merged and written to this protected location at runtime, Which would probably get the same error as for creating the cache files. 

So I'd suggest moving the files to a configurable static folder. This folder must then be marked in apache as a  static folder. This folder should be separate from the cache folder as we dont want to serve the cache folder. Although we can have a shared base path. E.g.  etc/arxivdigest/cache, etc/arxivdigest/static, etc/arxivdigest/config

Having defined a static folder in apache will most likely interfere with flasks static serving and would give us two options:

  * Put all static files in that folder
     * A perk of doing this is that apache can serve static files much more efficiently than flask.
     * Then it would be possible to not install the static files with the package. 
     * However  I would not want to move the location of the static files in the repository as this will make development much harder. This is because flask looks for a static folder inside the app when in debug mode. If we were to move these files we'd have to start using relative paths for static files, which always caused trouble and was one of the main reasons we created the package in the first place.
     * I would also like to keep the the templates as a part of the package as templates contain code and variables and cannot be served statically. 
  * Configure apache to only serve the javascript file from this location and reroute the other static request to flask as configured now.

I'll start implementing the functionality for needed for these methods, as the application code will be almost the same no matter how we decide to configure apache. And then we can discuss the details about duplicate staticfiles and locations when the code hopefully is able to run at Gustav.

**Comment by oyvi96** [comment] 2020-03-02 00:57
Finding a compromise between complicating development or deployment was harder than first expected. I think I may finally have been able to get something like method 1 above working, but this will require some more testing that I won't have time to do today. 

In case you're trying to deploy before I get this working it would be interesting if you'd try pasting this after assets = Environment(app), ca line 30 in app.py in frontend
 ```py
assets.auto_build = False

js_bundle = Bundle('javascript/autocomplete.js',
                   'javascript/forms.js',
                   'javascript/articlelist.js',
                   'javascript/admin.js',
                   'javascript/keywords.js',
                   filters='jsmin',
                   output='gen/js/base.%(version)s.js')
assets.register('js_base', js_bundle)

 ```
Then running the command either from the .wsgi location or frontend folder should work:
'sudo pip install .' or anaconda version
'sudo flask assets build' probably anaconda here also

and then checking in the arxivdigest.frontend.static.gen folder if a javascript file was created.

If you get this to work we won't have to change anything about the development method
and deployment would only add the extra flask assets build command.

Another similar alternative would be if the program had permission to write inside its own package location.

Of course open to other suggestions but do to the very different deployment methods for dev and prod many of the options are made very hard to implement without big sacrifices which would require a more advanced development/deployment strategy which we won't have time for implementing in this project.

**Comment by oyvi96** [comment] 2020-03-02 19:10
@kbalog 
I've published branch :  feature/#33_flask_static_files with a suggestion for how to solve this issue. I haven't created a pull request for it because we don't want to merge it if it does not work on gustav.

I feel this may be one of the least intrusive methods both for deployment and development, as it doesn't actually change any of the steps required for setting up or running.

**Closed** 2020-03-04 10:15 UTC
Labels: enhancement
